#!/bin/bash
# File              : run.sh
# Author            : Vushu <danvu.hustle@gmail.com>
# Date              : 03.09.2020
# Last Modified Date: 03.09.2020
# Last Modified By  : Vushu <danvu.hustle@gmail.com>

cd native && make
cd bin && ./TestGame
cd .. && cd ..  
